### PR TITLE
Fix library badge in ModMenu

### PR DESCRIPTION
**Pull request by halotroop2288**
(So it can be hidden.)

### CODE REVIEW

**Review by UpcraftLP — APPROVED** [review]

**Comment by UpcraftLP** [comment]
That looks alright, but how about all the other modules' fabric.mod.json files?

**Review by UpcraftLP — CHANGES_REQUESTED** [review]
missing changes to fabric.mod.json files for all other modules

**Comment by halotroop2288** [comment]
> missing changes to fabric.mod.json files for all other modules

Which modules specifically need to be changed? They look fine to me.

Actually, if I understand the ModMenu API correctly, everything except for Util looks like they're going overboard on the metadata.
But if you insist on doing it that way, Util would be the only one that needs changing.

**Comment by halotroop2288** [comment]
That should do it.

**Comment by halotroop2288** [comment]
@UpcraftLP Some input please?

**Review by Pyrofab — APPROVED** [review]
Thanks for your contribution !

**Pull request merged**
